title: The No-Crumbs Keto Kitchen
description: Keto-Friendly Recipes, Low Omega-6
baseurl: "/no-crumbs-keto-kitchen"
url: "https://lantzbuilds.github.io/no-crumbs-keto-kitchen"
theme: null
markdown: kramdown

include:
  - _includes/head_custom.html

defaults:
  - scope:
      path: ""
    values:
      head: head_custom.html

collections:
  recipes:
    output: true
    permalink: /recipes/:name.html

sass:
  load_paths:
    - _sass
  sass_dir: assets/css
